services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'user_management_system'
      MYSQL_USER: 'zyz'
      MYSQL_PASSWORD: 'nova_senha'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./user_management_api
    restart: always
    environment:
      DB_URL: mysql://zyz:nova_senha@db:3306/user_management_system
      SECRET_JWT: minha_chave_secreta
      MODE: RELEASE # DEV
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - db

  frontend:
    build: ./user_management_app
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - backend

volumes:
  db_data: